import {
  Project,
  Requirement,
  Task,
  Evidence,
  EvidenceLink,
  Review,
  ChangeRequest,
  HealthAlert,
  Evaluation,
  Rubric,
  VivaQuestion,
  LearningOutcome,
  Skill,
  Reflection,
} from '../types';

export const DEMO_USERS_MAP = {
  student1: {
    id: 'usr-student-belgin',
    email: 'belgin@projectflow.edu',
    fullName: 'Belgin C.',
    role: 'student' as const,
    institutionId: 'inst-ait-01',
    department: 'Computer Science & Engineering',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Belgin',
    isActive: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  student2: {
    id: 'usr-student-arun',
    email: 'arun@projectflow.edu',
    fullName: 'Arun Kumar',
    role: 'student' as const,
    institutionId: 'inst-ait-01',
    department: 'Computer Science & Engineering',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arun',
    isActive: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  student3: {
    id: 'usr-student-priya',
    email: 'priya@projectflow.edu',
    fullName: 'Priya Sundaram',
    role: 'student' as const,
    institutionId: 'inst-ait-01',
    department: 'Computer Science & Engineering',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PriyaS',
    isActive: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  student4: {
    id: 'usr-student-rahul',
    email: 'rahul@projectflow.edu',
    fullName: 'Rahul Verma',
    role: 'student' as const,
    institutionId: 'inst-ait-01',
    department: 'Computer Science & Engineering',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul',
    isActive: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  mentor: {
    id: 'usr-mentor-meena',
    email: 'mentor@projectflow.edu',
    fullName: 'Dr. Meena Swaminathan',
    role: 'mentor' as const,
    institutionId: 'inst-ait-01',
    department: 'Computer Science & Engineering',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meena',
    isActive: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  evaluator: {
    id: 'usr-evaluator-rajesh',
    email: 'evaluator@projectflow.edu',
    fullName: 'Prof. Rajesh Nair',
    role: 'evaluator' as const,
    institutionId: 'inst-ait-01',
    department: 'Electrical & Computer Engineering',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
    isActive: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
  admin: {
    id: 'usr-admin-sunita',
    email: 'admin@projectflow.edu',
    fullName: 'Dr. Sunita Kulkarni',
    role: 'institution_admin' as const,
    institutionId: 'inst-ait-01',
    department: 'Academic Dean Office',
    avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sunita',
    isActive: true,
    createdAt: '2026-08-01T09:00:00Z',
  },
};

export const INITIAL_PROJECT: Project = {
  id: 'proj-smart-campus-energy',
  institutionId: 'inst-ait-01',
  title: 'Smart Campus Energy Monitoring Platform',
  description:
    'University buildings consume significant electricity, but students and administrators lack a unified way to monitor usage and identify inefficient consumption in real time.',
  status: 'active',
  academicYear: '2026-2027',
  semester: 'Semester 7 - Capstone Phase I',
  mentorId: 'usr-mentor-meena',
  mentorName: 'Dr. Meena Swaminathan',
  team: {
    members: [
      { uid: 'usr-student-belgin', fullName: 'Belgin C.', email: 'belgin@projectflow.edu', projectRole: 'lead', joinedAt: '2026-08-10T10:00:00Z' },
      { uid: 'usr-student-arun', fullName: 'Arun Kumar', email: 'arun@projectflow.edu', projectRole: 'member', joinedAt: '2026-08-10T10:00:00Z' },
      { uid: 'usr-student-priya', fullName: 'Priya Sundaram', email: 'priya@projectflow.edu', projectRole: 'member', joinedAt: '2026-08-10T10:00:00Z' },
      { uid: 'usr-student-rahul', fullName: 'Rahul Verma', email: 'rahul@projectflow.edu', projectRole: 'member', joinedAt: '2026-08-10T10:00:00Z' },
    ],
  },
  createdBy: 'usr-student-belgin',
  createdAt: '2026-08-10T09:30:00Z',
  updatedAt: '2026-09-24T14:20:00Z',
};

export const INITIAL_REQUIREMENTS: Requirement[] = [
  {
    id: 'req-01',
    projectId: 'proj-smart-campus-energy',
    title: 'REQ-01: Student & Administrator Authentication',
    description: 'Secure JWT-based role separation allowing students, faculty, and facilities staff to access partitioned dashboards.',
    priority: 'critical',
    status: 'verified',
    acceptanceCriteria: [
      'Role-based route guarding for Student, Mentor, and Facility Admin',
      'Encrypted session tokens with automatic refresh handling',
      'Validation error feedback on invalid credential attempts',
    ],
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-09-20T16:00:00Z',
  },
  {
    id: 'req-02',
    projectId: 'proj-smart-campus-energy',
    title: 'REQ-02: Real-Time Energy Consumption Dashboard',
    description: 'High-density telemetry dashboard visualizing kilowatt-hour consumption per building wing with sub-second websocket refreshes.',
    priority: 'high',
    status: 'verified',
    acceptanceCriteria: [
      'Render live power consumption curves across 4 campus zones',
      'Interactive time-range selector (Live, 24H, 7D, 30D)',
      'Sub-500ms client chart rendering performance',
    ],
    createdAt: '2026-08-14T11:00:00Z',
    updatedAt: '2026-09-22T14:00:00Z',
  },
  {
    id: 'req-03',
    projectId: 'proj-smart-campus-energy',
    title: 'REQ-03: IoT Sensor Data Ingestion API',
    description: 'High-throughput authenticated REST API accepting JSON sensor payloads from smart energy meters across campus.',
    priority: 'critical',
    status: 'verified',
    acceptanceCriteria: [
      'Throughput capacity of >= 150 requests/sec with p95 < 80ms',
      'Strict schema validation rejecting negative and out-of-range sensor readings',
      'Signed API key authentication per physical meter node',
    ],
    createdAt: '2026-08-15T09:30:00Z',
    updatedAt: '2026-09-23T11:00:00Z',
  },
  {
    id: 'req-04',
    projectId: 'proj-smart-campus-energy',
    title: 'REQ-04: Consumption Analytics & Peak Demand Forecasting',
    description: 'Time-series predictive regression forecasting peak campus energy demand windows to prevent utility penalty surcharges.',
    priority: 'high',
    status: 'in_progress',
    acceptanceCriteria: [
      'Forecast peak demand within a 15% error margin for next 24 hours',
      'Highlight HVAC anomaly spikes in academic block B',
      'Exportable CSV and JSON inference outputs',
    ],
    createdAt: '2026-08-18T14:00:00Z',
    updatedAt: '2026-09-24T10:00:00Z',
  },
  {
    id: 'req-05',
    projectId: 'proj-smart-campus-energy',
    title: 'REQ-05: Automated High-Usage Alert System',
    description: 'Rule-driven alert notification system triggering notifications when power draw exceeds configured building thresholds.',
    priority: 'medium',
    status: 'in_progress',
    acceptanceCriteria: [
      'Configurable power draw limit threshold per lab/department',
      'Immediate alert dispatch upon 3 consecutive spike readings',
      'Audit log recorded for all triggered alerts',
    ],
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
  },
  {
    id: 'req-06',
    projectId: 'proj-smart-campus-energy',
    title: 'REQ-06: Institutional Sustainability Report Export',
    description: 'Automated generation of monthly carbon footprint and energy savings compliance reports for NAAC/ABET audits.',
    priority: 'medium',
    status: 'draft',
    acceptanceCriteria: [
      'Generate PDF summaries with comparative month-over-month trends',
      'Include verified sensor data checksums for academic integrity',
      'Signature block for Department Head endorsement',
    ],
    createdAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-08-25T11:00:00Z',
  },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'task-101',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-01',
    title: 'Implement JWT Authentication & Role-Based Guarding',
    description: 'Build JWT signing, validation middleware, and React router authorization guards for student, mentor, and admin personas.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-student-belgin',
    assigneeName: 'Belgin C.',
    dueDate: '2026-09-10',
    dependencies: [],
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-12T18:00:00Z',
  },
  {
    id: 'task-102',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-02',
    title: 'Design & Build Real-Time Energy Dashboard UI',
    description: 'Develop responsive telemetry charts, power usage sparklines, and status badges matching monochrome SaaS guidelines.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-student-priya',
    assigneeName: 'Priya Sundaram',
    dueDate: '2026-09-18',
    dependencies: ['task-101'],
    createdAt: '2026-08-16T11:00:00Z',
    updatedAt: '2026-09-17T17:00:00Z',
  },
  {
    id: 'task-103',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-03',
    title: 'Build IoT Sensor Telemetry REST Ingestion API',
    description: 'Create high-throughput ingestion endpoint with rate limiting, signature verification, and payload validation.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-student-arun',
    assigneeName: 'Arun Kumar',
    dueDate: '2026-09-16',
    dependencies: [],
    createdAt: '2026-08-17T10:00:00Z',
    updatedAt: '2026-09-18T16:00:00Z',
  },
  {
    id: 'task-104',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-03',
    title: 'Design Time-Series Database Schema & Partitioning',
    description: 'Architect PostgreSQL / Timescale hypertable schema with indexes on meter_id, timestamp, and active_power.',
    status: 'done',
    priority: 'medium',
    assigneeId: 'usr-student-arun',
    assigneeName: 'Arun Kumar',
    dueDate: '2026-09-14',
    dependencies: [],
    createdAt: '2026-08-15T12:00:00Z',
    updatedAt: '2026-09-15T19:00:00Z',
  },
  {
    id: 'task-105',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-03',
    title: 'Implement Sensor Payload Validation (Response to Mentor CR-01)',
    description: 'Implement rigorous validation layer that rejects negative energy readings and logs diagnostic warnings.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-student-arun',
    assigneeName: 'Arun Kumar',
    dueDate: '2026-09-22',
    dependencies: ['task-103'],
    createdAt: '2026-09-20T10:00:00Z',
    updatedAt: '2026-09-22T15:30:00Z',
  },
  {
    id: 'task-106',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-04',
    title: 'Train Energy Demand Forecasting & Anomaly Model',
    description: 'Develop LSTM regression model in Python to predict 24-hour campus peak demand patterns.',
    status: 'in_progress',
    priority: 'medium',
    assigneeId: 'usr-student-rahul',
    assigneeName: 'Rahul Verma',
    dueDate: '2026-09-30',
    dependencies: ['task-104'],
    createdAt: '2026-08-22T10:00:00Z',
    updatedAt: '2026-09-24T16:00:00Z',
  },
  {
    id: 'task-107',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-01',
    title: 'Automated Integration & Load Testing Suite',
    description: 'Author automated end-to-end integration and load tests simulating 100 concurrent smart meter telemetry streams.',
    status: 'done',
    priority: 'high',
    assigneeId: 'usr-student-belgin',
    assigneeName: 'Belgin C.',
    dueDate: '2026-09-21',
    dependencies: ['task-101', 'task-103'],
    createdAt: '2026-09-19T09:00:00Z',
    updatedAt: '2026-09-21T18:00:00Z',
  },
  {
    id: 'task-108',
    projectId: 'proj-smart-campus-energy',
    requirementId: 'req-02',
    title: 'Deploy Staging Instance with Docker & Health Checks',
    description: 'Configure multi-stage Docker containerization and deploy verified staging URL for faculty review.',
    status: 'done',
    priority: 'medium',
    assigneeId: 'usr-student-belgin',
    assigneeName: 'Belgin C.',
    dueDate: '2026-09-23',
    dependencies: ['task-102', 'task-107'],
    createdAt: '2026-09-22T10:00:00Z',
    updatedAt: '2026-09-23T14:00:00Z',
  },
];

export const INITIAL_EVIDENCE: Evidence[] = [
  {
    id: 'ev-01',
    projectId: 'proj-smart-campus-energy',
    ownerId: 'usr-student-belgin',
    ownerName: 'Belgin C.',
    type: 'github_pr',
    title: 'GitHub PR #42: JWT Authentication & Role Interceptors',
    description: 'Implements cryptographic JWT bearer token validation, refresh rotation, and protected React routing.',
    sourceType: 'github',
    sourceUrl: 'https://github.com/projectflow-ait/smart-campus-energy/pull/42',
    verificationStatus: 'mentor_verified',
    verificationComment: 'Clean security architecture with automated unit tests for role guards. Verified and approved.',
    verifiedBy: 'usr-mentor-meena',
    verifiedByName: 'Dr. Meena Swaminathan',
    verifiedAt: '2026-09-13T10:30:00Z',
    createdAt: '2026-09-12T18:30:00Z',
    updatedAt: '2026-09-13T10:30:00Z',
  },
  {
    id: 'ev-02',
    projectId: 'proj-smart-campus-energy',
    ownerId: 'usr-student-priya',
    ownerName: 'Priya Sundaram',
    type: 'screenshot',
    title: 'Live Telemetry Dashboard UI & Sparklines Preview',
    description: 'High-contrast monochrome energy monitoring cards showing real-time kW draw, load factor, and zone breakdown.',
    sourceType: 'upload',
    fileName: 'campus_energy_dashboard_v1.png',
    sourceUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    verificationStatus: 'mentor_verified',
    verificationComment: 'Accessible design system with clear visual hierarchy and responsive chart rendering.',
    verifiedBy: 'usr-mentor-meena',
    verifiedByName: 'Dr. Meena Swaminathan',
    verifiedAt: '2026-09-18T11:00:00Z',
    createdAt: '2026-09-17T17:30:00Z',
    updatedAt: '2026-09-18T11:00:00Z',
  },
  {
    id: 'ev-03',
    projectId: 'proj-smart-campus-energy',
    ownerId: 'usr-student-arun',
    ownerName: 'Arun Kumar',
    type: 'test_result',
    title: 'Telemetry Ingestion API Benchmark Test Suite (Initial)',
    description: 'Locust load test results demonstrating sustained 160 requests/sec with p95 response time of 68ms.',
    sourceType: 'upload',
    fileName: 'sensor_api_benchmark_report.pdf',
    verificationStatus: 'needs_revision',
    verificationComment: 'Throughput is excellent, but tests show endpoint does not reject negative energy readings. Revision required.',
    verifiedBy: 'usr-mentor-meena',
    verifiedByName: 'Dr. Meena Swaminathan',
    verifiedAt: '2026-09-19T14:00:00Z',
    createdAt: '2026-09-18T16:30:00Z',
    updatedAt: '2026-09-19T14:00:00Z',
  },
  {
    id: 'ev-04',
    projectId: 'proj-smart-campus-energy',
    ownerId: 'usr-student-arun',
    ownerName: 'Arun Kumar',
    type: 'document',
    title: 'Database Architecture Schema & Timescale Time-Series Model',
    description: 'Normalized database schema specification showing hypertable chunks, composite indexes, and compression policies.',
    sourceType: 'upload',
    fileName: 'timeseries_schema_architecture.pdf',
    verificationStatus: 'mentor_verified',
    verificationComment: 'Appropriate chunk interval of 7 days with effective automated rollup views for hourly aggregations.',
    verifiedBy: 'usr-mentor-meena',
    verifiedByName: 'Dr. Meena Swaminathan',
    verifiedAt: '2026-09-16T15:00:00Z',
    createdAt: '2026-09-15T19:30:00Z',
    updatedAt: '2026-09-16T15:00:00Z',
  },
  {
    id: 'ev-05',
    projectId: 'proj-smart-campus-energy',
    ownerId: 'usr-student-arun',
    ownerName: 'Arun Kumar',
    type: 'github_pr',
    title: 'GitHub PR #48: Sensor Ingestion Validation (Resolves CR-01)',
    description: 'Implements strict pydantic validator checking active_power >= 0.0 with automated 422 HTTP validation tests.',
    sourceType: 'github',
    sourceUrl: 'https://github.com/projectflow-ait/smart-campus-energy/pull/48',
    verificationStatus: 'mentor_verified',
    verificationComment: 'Change request CR-01 successfully addressed. Negative readings are properly rejected with validation logs.',
    verifiedBy: 'usr-mentor-meena',
    verifiedByName: 'Dr. Meena Swaminathan',
    verifiedAt: '2026-09-23T11:00:00Z',
    createdAt: '2026-09-22T16:00:00Z',
    updatedAt: '2026-09-23T11:00:00Z',
  },
  {
    id: 'ev-06',
    projectId: 'proj-smart-campus-energy',
    ownerId: 'usr-student-belgin',
    ownerName: 'Belgin C.',
    type: 'test_result',
    title: 'Automated End-to-End Test Suite & 94% Code Coverage Report',
    description: 'Integration test run verifying auth guards, telemetry ingestion, websocket broadcasts, and error handling.',
    sourceType: 'upload',
    fileName: 'e2e_coverage_report_v1.html',
    verificationStatus: 'mentor_verified',
    verificationComment: 'Solid coverage across all critical paths. All 42 integration test suites pass reliably.',
    verifiedBy: 'usr-mentor-meena',
    verifiedByName: 'Dr. Meena Swaminathan',
    verifiedAt: '2026-09-22T10:00:00Z',
    createdAt: '2026-09-21T18:30:00Z',
    updatedAt: '2026-09-22T10:00:00Z',
  },
  {
    id: 'ev-07',
    projectId: 'proj-smart-campus-energy',
    ownerId: 'usr-student-belgin',
    ownerName: 'Belgin C.',
    type: 'demo_video',
    title: 'Staging Deployment URL & Live Verification Probe',
    description: 'Working live demo link running containerized on university cloud infrastructure with live simulated meter streams.',
    sourceType: 'link',
    sourceUrl: 'https://smart-energy-staging.ait.edu',
    verificationStatus: 'mentor_verified',
    verificationComment: 'Demonstrated live in laboratory setting. Real-time updates and latency targets verified.',
    verifiedBy: 'usr-mentor-meena',
    verifiedByName: 'Dr. Meena Swaminathan',
    verifiedAt: '2026-09-24T12:00:00Z',
    createdAt: '2026-09-23T14:30:00Z',
    updatedAt: '2026-09-24T12:00:00Z',
  },
];

export const INITIAL_EVIDENCE_LINKS: EvidenceLink[] = [
  { id: 'lnk-01', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-01', entityId: 'task-101', entityType: 'task', relationshipType: 'implements', targetId: 'task-101', targetType: 'task', relationship: 'implements', createdAt: '2026-09-12T18:30:00Z' },
  { id: 'lnk-02', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-01', entityId: 'req-01', entityType: 'requirement', relationshipType: 'proves', targetId: 'req-01', targetType: 'requirement', relationship: 'proves', createdAt: '2026-09-12T18:30:00Z' },
  { id: 'lnk-03', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-02', entityId: 'task-102', entityType: 'task', relationshipType: 'implements', targetId: 'task-102', targetType: 'task', relationship: 'implements', createdAt: '2026-09-17T17:30:00Z' },
  { id: 'lnk-04', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-02', entityId: 'req-02', entityType: 'requirement', relationshipType: 'proves', targetId: 'req-02', targetType: 'requirement', relationship: 'proves', createdAt: '2026-09-17T17:30:00Z' },
  { id: 'lnk-05', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-03', entityId: 'task-103', entityType: 'task', relationshipType: 'tests', targetId: 'task-103', targetType: 'task', relationship: 'tests', createdAt: '2026-09-18T16:30:00Z' },
  { id: 'lnk-06', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-03', entityId: 'req-03', entityType: 'requirement', relationshipType: 'supports', targetId: 'req-03', targetType: 'requirement', relationship: 'supports', createdAt: '2026-09-18T16:30:00Z' },
  { id: 'lnk-07', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-04', entityId: 'task-104', entityType: 'task', relationshipType: 'implements', targetId: 'task-104', targetType: 'task', relationship: 'implements', createdAt: '2026-09-15T19:30:00Z' },
  { id: 'lnk-08', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-04', entityId: 'req-03', entityType: 'requirement', relationshipType: 'supports', targetId: 'req-03', targetType: 'requirement', relationship: 'supports', createdAt: '2026-09-15T19:30:00Z' },
  { id: 'lnk-09', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-05', entityId: 'task-105', entityType: 'task', relationshipType: 'implements', targetId: 'task-105', targetType: 'task', relationship: 'implements', createdAt: '2026-09-22T16:00:00Z' },
  { id: 'lnk-10', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-05', entityId: 'req-03', entityType: 'requirement', relationshipType: 'proves', targetId: 'req-03', targetType: 'requirement', relationship: 'proves', createdAt: '2026-09-22T16:00:00Z' },
  { id: 'lnk-11', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-06', entityId: 'task-107', entityType: 'task', relationshipType: 'tests', targetId: 'task-107', targetType: 'task', relationship: 'tests', createdAt: '2026-09-21T18:30:00Z' },
  { id: 'lnk-12', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-06', entityId: 'req-01', entityType: 'requirement', relationshipType: 'proves', targetId: 'req-01', targetType: 'requirement', relationship: 'proves', createdAt: '2026-09-21T18:30:00Z' },
  { id: 'lnk-13', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-07', entityId: 'task-108', entityType: 'task', relationshipType: 'implements', targetId: 'task-108', targetType: 'task', relationship: 'implements', createdAt: '2026-09-23T14:30:00Z' },
  { id: 'lnk-14', projectId: 'proj-smart-campus-energy', evidenceId: 'ev-07', entityId: 'req-02', entityType: 'requirement', relationshipType: 'proves', targetId: 'req-02', targetType: 'requirement', relationship: 'proves', createdAt: '2026-09-23T14:30:00Z' },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-01',
    projectId: 'proj-smart-campus-energy',
    evidenceId: 'ev-01',
    reviewerId: 'usr-mentor-meena',
    reviewerName: 'Dr. Meena Swaminathan',
    status: 'approved',
    comments: 'Exceptional security implementation. Refresh token rotation is handled securely and unit tests are comprehensive.',
    createdAt: '2026-09-13T10:30:00Z',
    updatedAt: '2026-09-13T10:30:00Z',
  },
  {
    id: 'rev-02',
    projectId: 'proj-smart-campus-energy',
    evidenceId: 'ev-03',
    reviewerId: 'usr-mentor-meena',
    reviewerName: 'Dr. Meena Swaminathan',
    status: 'revision_requested',
    comments: 'Add validation for invalid sensor readings. Current test payload accepted negative kilowatt values without raising validation exceptions.',
    changeRequestId: 'cr-01',
    createdAt: '2026-09-19T14:00:00Z',
    updatedAt: '2026-09-19T14:00:00Z',
  },
  {
    id: 'rev-03',
    projectId: 'proj-smart-campus-energy',
    evidenceId: 'ev-05',
    reviewerId: 'usr-mentor-meena',
    reviewerName: 'Dr. Meena Swaminathan',
    status: 'approved',
    comments: 'Validation logic verified. Automated tests now assert 422 Unprocessable Entity whenever negative power readings are submitted.',
    createdAt: '2026-09-23T11:00:00Z',
    updatedAt: '2026-09-23T11:00:00Z',
  },
];

export const INITIAL_CHANGE_REQUESTS: ChangeRequest[] = [
  {
    id: 'cr-01',
    projectId: 'proj-smart-campus-energy',
    reviewId: 'rev-02',
    title: 'CR-01: Sensor Data Negative Value Validation',
    description: 'Reject negative energy readings and display a validation message with structured HTTP 422 response.',
    requiredEvidenceType: 'github_pr',
    status: 'verified',
    dueDate: '2026-09-23',
    assigneeId: 'usr-student-arun',
    assigneeName: 'Arun Kumar',
    resolvedEvidenceId: 'ev-05',
    createdAt: '2026-09-19T14:00:00Z',
    updatedAt: '2026-09-23T11:00:00Z',
  },
];

export const INITIAL_HEALTH_ALERTS: HealthAlert[] = [
  {
    id: 'alert-01',
    projectId: 'proj-smart-campus-energy',
    alertType: 'missing_evidence',
    severity: 'warning',
    category: 'missing_evidence',
    title: 'Requirement REQ-06 Missing Empirical Evidence',
    reason: 'Requirement "Institutional Sustainability Report Export" is in draft state with zero associated tasks or verified evidence.',
    description: 'Requirement "Institutional Sustainability Report Export" is in draft state with zero associated tasks or verified evidence.',
    affectedEntityId: 'req-06',
    affectedEntityType: 'requirement',
    suggestedAction: 'Create implementation tasks and attach initial PDF template specification.',
    createdAt: '2026-09-24T08:00:00Z',
  },
  {
    id: 'alert-02',
    projectId: 'proj-smart-campus-energy',
    alertType: 'missing_testing',
    severity: 'info',
    category: 'unverified_work',
    title: 'Task-106 (Consumption ML Model) in Progress',
    reason: 'Active task requires testing evidence artifact before final Phase I capstone evaluation.',
    description: 'Active task requires testing evidence artifact before final Phase I capstone evaluation.',
    affectedEntityId: 'task-106',
    affectedEntityType: 'task',
    suggestedAction: 'Upload ML model validation curve and F1/RMSE metric report.',
    createdAt: '2026-09-24T09:00:00Z',
  },
];

export const INITIAL_RUBRICS: Rubric[] = [
  {
    id: 'rubric-ait-capstone-v1',
    institutionId: 'inst-ait-01',
    title: 'Academic Capstone Project & Evidence-Based Rubric',
    description: 'Accredited university rubric mapping verified artifacts to ABET / NBA continuous improvement standards.',
    criteria: [
      { id: 'crit-01', name: 'Problem Understanding & Requirements Specification', description: 'Traceability and clarity of user stories and acceptance criteria', maxScore: 10, weightage: 10 },
      { id: 'crit-02', name: 'Technical Architecture & Implementation Rigor', description: 'Quality of source code, modularity, and database architecture supported by verified PRs', maxScore: 25, weightage: 25 },
      { id: 'crit-03', name: 'Testing, Validation & Reliability Verification', description: 'Automated test suite coverage, edge case handling, and benchmark evidence', maxScore: 15, weightage: 15 },
      { id: 'crit-04', name: 'Responsiveness to Mentor Feedback & Change Requests', description: 'Demonstrated resolution of change requests with verified revision artifacts', maxScore: 15, weightage: 15 },
      { id: 'crit-05', name: 'Engineering Documentation & Artifact Traceability', description: 'Completeness of schemas, architecture diagrams, and deployment artifacts', maxScore: 15, weightage: 15 },
      { id: 'crit-06', name: 'Viva Voce & Technical Defensibility', description: 'Individual mastery of technical decisions evidenced through oral examination', maxScore: 20, weightage: 20 },
    ],
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-01T09:00:00Z',
  },
];

export const INITIAL_EVALUATIONS: Evaluation[] = [
  {
    id: 'eval-ait-smart-energy-01',
    projectId: 'proj-smart-campus-energy',
    rubricId: 'rubric-ait-capstone-v1',
    rubricTitle: 'Academic Capstone Project & Evidence-Based Rubric',
    evaluatorId: 'usr-evaluator-rajesh',
    evaluatorName: 'Prof. Rajesh Nair',
    overallScore: 92,
    maxTotalScore: 100,
    feedback: 'Outstanding technical execution. The team demonstrated rigorous responsiveness to mentor feedback with verified revision evidence for negative telemetry validation.',
    status: 'draft',
    scores: [
      { criterionId: 'crit-01', criterionName: 'Problem Understanding & Requirements Specification', score: 9.5, maxScore: 10, comment: 'High quality user stories with clear acceptance criteria across all 6 requirements.', evidenceIds: ['ev-01', 'ev-02'] },
      { criterionId: 'crit-02', criterionName: 'Technical Architecture & Implementation Rigor', score: 24, maxScore: 25, comment: 'Verified PR #42 and Timescale hypertable architecture exhibit professional modularity.', evidenceIds: ['ev-01', 'ev-04', 'ev-07'] },
      { criterionId: 'crit-03', criterionName: 'Testing, Validation & Reliability Verification', score: 14, maxScore: 15, comment: 'Automated test suite with 94% coverage verified through empirical report ev-06.', evidenceIds: ['ev-06', 'ev-03'] },
      { criterionId: 'crit-04', criterionName: 'Responsiveness to Mentor Feedback & Change Requests', score: 15, maxScore: 15, comment: 'CR-01 resolved completely with PR #48 adding negative telemetry validation.', evidenceIds: ['ev-05'] },
      { criterionId: 'crit-05', criterionName: 'Engineering Documentation & Artifact Traceability', score: 13.5, maxScore: 15, comment: 'Architecture schemas and deployment staging probe fully verified.', evidenceIds: ['ev-04', 'ev-07'] },
      { criterionId: 'crit-06', criterionName: 'Viva Voce & Technical Defensibility', score: 16, maxScore: 20, comment: 'Solid student defense during technical viva examination.', evidenceIds: ['ev-01', 'ev-05'] },
    ],
    createdAt: '2026-09-24T15:00:00Z',
    updatedAt: '2026-09-24T16:30:00Z',
  },
];

export const INITIAL_VIVA_QUESTIONS: VivaQuestion[] = [
  {
    id: 'viva-q1',
    projectId: 'proj-smart-campus-energy',
    studentId: 'usr-student-belgin',
    studentName: 'Belgin C.',
    question: 'In PR #42 you implemented JWT authentication with short-lived tokens and refresh rotation. What attack vector does this specific rotation mechanism mitigate compared to long-lived stateless JWTs?',
    groundingEvidenceId: 'ev-01',
    groundingContext: 'Linked to Requirement REQ-01, Task-101, and GitHub PR #42.',
    studentAnswer: 'Short-lived tokens limit the blast radius if an access token is intercepted via XSS or network sniffing. Refresh token rotation ensures that when a new access token is requested, the previous refresh token is invalidated. If an attacker replays a compromised refresh token, the auth server detects the reuse anomaly and revokes the entire token family.',
    evaluatorNotes: 'Precise understanding of token family revocation and theft detection. Full marks.',
    score: 10,
    status: 'answered',
    createdAt: '2026-09-24T11:00:00Z',
  },
  {
    id: 'viva-q2',
    projectId: 'proj-smart-campus-energy',
    studentId: 'usr-student-arun',
    studentName: 'Arun Kumar',
    question: 'During initial benchmark testing, Dr. Meena flagged that your sensor ingestion API accepted negative energy readings. How did you resolve Change Request CR-01 in PR #48 without compromising the 160 req/s throughput target?',
    groundingEvidenceId: 'ev-05',
    groundingContext: 'Linked to Change Request CR-01, Task-105, and GitHub PR #48.',
    studentAnswer: 'We added a lightweight Pydantic pre-validator directly on the fast ingestion schema to assert active_power >= 0.0 before entering database transaction pools. Because the check occurs in-memory at deserialize time with zero secondary DB queries, latency overhead was negligible (under 0.3ms), maintaining our p95 latency at 68ms.',
    evaluatorNotes: 'Excellent balance between data integrity guarantees and throughput performance.',
    score: 10,
    status: 'answered',
    createdAt: '2026-09-24T11:15:00Z',
  },
  {
    id: 'viva-q3',
    projectId: 'proj-smart-campus-energy',
    studentId: 'usr-student-priya',
    studentName: 'Priya Sundaram',
    question: 'How did you ensure sub-second rendering latency on the energy telemetry dashboard when streaming high-frequency data for four simultaneous campus zones?',
    groundingEvidenceId: 'ev-02',
    groundingContext: 'Linked to Requirement REQ-02, Task-102, and UI Dashboard Screenshot ev-02.',
    studentAnswer: 'We implemented client-side window downsampling using the Largest-Triangle-Three-Buckets (LTTB) algorithm before passing point arrays into SVG sparklines. This keeps DOM node count strictly constant (100 points) regardless of whether the meter has recorded 1,000 or 100,000 data points.',
    evaluatorNotes: 'Thorough grasp of client-side visualization optimizations.',
    score: 9.5,
    status: 'answered',
    createdAt: '2026-09-24T11:30:00Z',
  },
];

export const INITIAL_OUTCOMES: LearningOutcome[] = [
  {
    id: 'lo-01',
    code: 'PO-01',
    title: 'Engineering Knowledge & Complex Problem Solving',
    description: 'Apply software engineering principles and mathematics to design robust IoT telemetry platforms.',
    category: 'program_outcome',
    bloomLevel: 'Apply',
  },
  {
    id: 'lo-02',
    code: 'PO-02',
    title: 'Problem Analysis & Data Validation',
    description: 'Identify and address validation vulnerabilities in continuous sensor telemetry data pipelines.',
    category: 'program_outcome',
    bloomLevel: 'Analyze',
  },
  {
    id: 'lo-03',
    code: 'PO-03',
    title: 'Design/Development of Scalable Solutions',
    description: 'Design time-series storage and real-time dashboard interfaces meeting institutional monitoring needs.',
    category: 'program_outcome',
    bloomLevel: 'Create',
  },
  {
    id: 'lo-04',
    code: 'PO-05',
    title: 'Modern Tool Usage & Continuous Integration',
    description: 'Utilize automated CI/CD pipelines, Docker containerization, and test coverage tooling.',
    category: 'program_outcome',
    bloomLevel: 'Apply',
  },
  {
    id: 'lo-05',
    code: 'PO-09',
    title: 'Individual Work & Multidisciplinary Teamwork',
    description: 'Collaborate effectively in agile roles across full-stack, ML, design, and backend disciplines.',
    category: 'program_outcome',
    bloomLevel: 'Evaluate',
  },
];

export const INITIAL_SKILLS: Skill[] = [
  { id: 'sk-01', name: 'TypeScript & React Architecture', category: 'Frontend', verifiedEvidenceCount: 4 },
  { id: 'sk-02', name: 'RESTful API & Telemetry Ingestion', category: 'Backend', verifiedEvidenceCount: 3 },
  { id: 'sk-03', name: 'Timescale / PostgreSQL Time-Series Modeling', category: 'Database', verifiedEvidenceCount: 2 },
  { id: 'sk-04', name: 'Automated CI/CD & Docker Containerization', category: 'DevOps', verifiedEvidenceCount: 2 },
  { id: 'sk-05', name: 'Security & Cryptographic JWT Authentication', category: 'Security', verifiedEvidenceCount: 2 },
];

export const INITIAL_REFLECTIONS: Reflection[] = [
  {
    id: 'ref-01',
    projectId: 'proj-smart-campus-energy',
    userId: 'usr-student-belgin',
    authorName: 'Belgin C.',
    milestoneTitle: 'Phase I Capstone Architecture & Deployment',
    content: 'Building the end-to-end telemetry architecture helped bridge theoretical distributed systems concepts with real-world IoT constraints. Implementing strict JWT role isolation early made subsequent API endpoint development much safer.',
    challenges: 'Ensuring sub-second websocket refreshes while handling simulated burst traffic from multiple campus buildings.',
    learnings: 'Decoupling sensor ingestion from visualization data downsampling was crucial to avoid UI freezes.',
    createdAt: '2026-09-24T14:00:00Z',
  },
  {
    id: 'ref-02',
    projectId: 'proj-smart-campus-energy',
    userId: 'usr-student-arun',
    authorName: 'Arun Kumar',
    milestoneTitle: 'Sensor API Validation & Resolution of CR-01',
    content: 'Dr. Meena’s feedback regarding negative readings highlighted that telemetry pipelines cannot trust physical sensor hardware implicitly. Resolving CR-01 with in-memory validation taught us defensible API design.',
    challenges: 'Handling malformed sensor packets without slowing down overall throughput.',
    learnings: 'Validation at the schema boundary is significantly faster than relying on database trigger constraints.',
    createdAt: '2026-09-24T14:30:00Z',
  },
];

export const INITIAL_IDEAS = [
  {
    id: 'idea-01',
    title: 'Autonomous Drone Surface Defect Inspection for Campus Solar Arrays',
    problemStatement: 'Manual inspection of rooftop photovoltaic panels is hazardous and time-consuming. Using computer vision models on low-cost quadcopters allows automated hotspot and micro-crack detection.',
    domain: 'Computer Vision & Renewable Energy',
    requiredSkills: ['Python', 'YOLOv8', 'Edge Computing', 'PyTorch'],
    proposedBy: 'usr-mentor-meena',
    proposedByName: 'Dr. Meena Swaminathan',
    role: 'mentor' as const,
    status: 'open' as const,
    joinRequests: [
      { userId: 'usr-student-rahul', userName: 'Rahul Verma', message: 'I have experience in drone telemetry and object detection models.', createdAt: '2026-09-20T10:00:00Z' }
    ],
    createdAt: '2026-09-15T09:00:00Z',
  },
  {
    id: 'idea-02',
    title: 'Decentralized Microgrid Energy Arbitrage Simulation',
    problemStatement: 'Simulate peer-to-peer energy trading between academic department buildings with rooftop solar generation and battery energy storage systems.',
    domain: 'Smart Grid & Distributed Systems',
    requiredSkills: ['TypeScript', 'Optimization Algorithms', 'Time-series', 'FastAPI'],
    proposedBy: 'usr-student-belgin',
    proposedByName: 'Belgin C.',
    role: 'student' as const,
    status: 'open' as const,
    joinRequests: [],
    createdAt: '2026-09-18T14:00:00Z',
  },
  {
    id: 'idea-03',
    title: 'Privacy-Preserving Edge Voice Assistant for Laboratory Safety',
    problemStatement: 'Hands-free emergency voice logging and reagent safety checking without streaming audio streams outside local university server boundaries.',
    domain: 'Speech AI & Embedded Systems',
    requiredSkills: ['Whisper.cpp', 'C++', 'FastAPI', 'WebSockets'],
    proposedBy: 'usr-mentor-meena',
    proposedByName: 'Dr. Meena Swaminathan',
    role: 'mentor' as const,
    status: 'open' as const,
    joinRequests: [],
    createdAt: '2026-09-22T11:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-01',
    userId: 'usr-student-belgin',
    title: 'Evidence Verified',
    message: 'Dr. Meena Swaminathan approved GitHub PR #42 (JWT Authentication & Role Interceptors).',
    type: 'success' as const,
    isRead: false,
    link: '/evidence',
    createdAt: '2026-09-13T10:30:00Z',
  },
  {
    id: 'notif-02',
    userId: 'usr-student-arun',
    title: 'Change Request Created',
    message: 'Dr. Meena created Change Request CR-01: Sensor Data Negative Value Validation.',
    type: 'warning' as const,
    isRead: false,
    link: '/reviews',
    createdAt: '2026-09-19T14:00:00Z',
  },
  {
    id: 'notif-03',
    userId: 'usr-student-arun',
    title: 'Change Request Verified',
    message: 'CR-01 verified by Dr. Meena following PR #48 submission.',
    type: 'success' as const,
    isRead: true,
    link: '/reviews',
    createdAt: '2026-09-23T11:00:00Z',
  },
  {
    id: 'notif-04',
    userId: 'usr-student-belgin',
    title: 'Project Health Diagnostic Update',
    message: 'Requirement REQ-06 missing testing evidence before upcoming Phase I review.',
    type: 'alert' as const,
    isRead: false,
    link: '/health',
    createdAt: '2026-09-24T08:00:00Z',
  },
];
